# -*- coding: utf-8 -*-
"""coursework1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12_JXBiXwljzOaOe5McEKcQQuLhtw0_Qn
"""

import numpy as np 
import random
import matplotlib.pyplot as plt # Graphical library
#from sklearn.metrics import mean_squared_error # Mean-squared error function

"""# Coursework 1 :
See pdf for instructions. 
"""

# WARNING: fill in these two functions that will be used by the auto-marking script
# [Action required]

def get_CID():
  return "01549029" # Return your CID (add 0 at the beginning to ensure it is 8 digits long)

def get_login():
  return "ls4918" # Return your short imperial login

"""## Helper class"""

# This class is used ONLY for graphics
# YOU DO NOT NEED to understand it to work on this coursework

class GraphicsMaze(object):

  def __init__(self, shape, locations, default_reward, obstacle_locs, absorbing_locs, absorbing_rewards, absorbing):

    self.shape = shape
    self.locations = locations
    self.absorbing = absorbing

    # Walls
    self.walls = np.zeros(self.shape)
    for ob in obstacle_locs:
      self.walls[ob] = 20

    # Rewards
    self.rewarders = np.ones(self.shape) * default_reward
    for i, rew in enumerate(absorbing_locs):
      self.rewarders[rew] = 10 if absorbing_rewards[i] > 0 else -10

    # Print the map to show it
    self.paint_maps()

  def paint_maps(self):
    """
    Print the Maze topology (obstacles, absorbing states and rewards)
    input: /
    output: /
    """
    plt.figure(figsize=(15,10))
    plt.imshow(self.walls + self.rewarders)
    plt.show()

  def paint_state(self, state):
    """
    Print one state on the Maze topology (obstacles, absorbing states and rewards)
    input: /
    output: /
    """
    states = np.zeros(self.shape)
    states[state] = 30
    plt.figure(figsize=(15,10))
    plt.imshow(self.walls + self.rewarders + states)
    plt.show()

  def draw_deterministic_policy(self, Policy):
    """
    Draw a deterministic policy
    input: Policy {np.array} -- policy to draw (should be an array of values between 0 and 3 (actions))
    output: /
    """
    plt.figure(figsize=(15,10))
    plt.imshow(self.walls + self.rewarders) # Create the graph of the Maze
    for state, action in enumerate(Policy):
      if(self.absorbing[0,state]): # If it is an absorbing state, don't plot any action
        continue
      arrows = [r"$\uparrow$",r"$\rightarrow$", r"$\downarrow$", r"$\leftarrow$"] # List of arrows corresponding to each possible action
      action_arrow = arrows[action] # Take the corresponding action
      location = self.locations[state] # Compute its location on graph
      plt.text(location[1], location[0], action_arrow, ha='center', va='center') # Place it on graph 
    plt.show()

  def draw_policy(self, Policy):
    """
    Draw a policy (draw an arrow in the most probable direction)
    input: Policy {np.array} -- policy to draw as probability
    output: /
    """
    deterministic_policy = np.array([np.argmax(Policy[row,:]) for row in range(Policy.shape[0])])
    self.draw_deterministic_policy(deterministic_policy)

  def draw_value(self, Value):
    """
    Draw a policy value
    input: Value {np.array} -- policy values to draw
    output: /
    """
    plt.figure(figsize=(15,10))
    plt.imshow(self.walls + self.rewarders) # Create the graph of the Maze
    for state, value in enumerate(Value):
      if(self.absorbing[0, state]): # If it is an absorbing state, don't plot any value
        continue
      location = self.locations[state] # Compute the value location on graph
      plt.text(location[1], location[0], round(value,2), ha='center', va='center') # Place it on graph
    plt.show()

  def draw_deterministic_policy_grid(self, Policies, title, n_columns, n_lines):
    """
    Draw a grid representing multiple deterministic policies
    input: Policies {np.array of np.array} -- array of policies to draw (each should be an array of values between 0 and 3 (actions))
    output: /
    """
    plt.figure(figsize=(20,8))
    for subplot in range (len(Policies)): # Go through all policies
      ax = plt.subplot(n_columns, n_lines, subplot+1) # Create a subplot for each policy
      ax.imshow(self.walls+self.rewarders) # Create the graph of the Maze
      for state, action in enumerate(Policies[subplot]):
        if(self.absorbing[0,state]): # If it is an absorbing state, don't plot any action
          continue
        arrows = [r"$\uparrow$",r"$\rightarrow$", r"$\downarrow$", r"$\leftarrow$"] # List of arrows corresponding to each possible action
        action_arrow = arrows[action] # Take the corresponding action
        location = self.locations[state] # Compute its location on graph
        plt.text(location[1], location[0], action_arrow, ha='center', va='center') # Place it on graph
      ax.title.set_text(title[subplot]) # Set the title for the graph given as argument
    plt.show()

  def draw_policy_grid(self, Policies, title, n_columns, n_lines):
    """
    Draw a grid representing multiple policies (draw an arrow in the most probable direction)
    input: Policy {np.array} -- array of policies to draw as probability
    output: /
    """
    deterministic_policies = np.array([[np.argmax(Policy[row,:]) for row in range(Policy.shape[0])] for Policy in Policies])
    self.draw_deterministic_policy_grid(deterministic_policies, title, n_columns, n_lines)

  def draw_value_grid(self, Values, title, n_columns, n_lines):
    """
    Draw a grid representing multiple policy values
    input: Values {np.array of np.array} -- array of policy values to draw
    output: /
    """
    plt.figure(figsize=(20,8))
    for subplot in range (len(Values)): # Go through all values
      ax = plt.subplot(n_columns, n_lines, subplot+1) # Create a subplot for each value
      ax.imshow(self.walls+self.rewarders) # Create the graph of the Maze
      for state, value in enumerate(Values[subplot]):
        if(self.absorbing[0,state]): # If it is an absorbing state, don't plot any value
          continue
        location = self.locations[state] # Compute the value location on graph
        plt.text(location[1], location[0], round(value,1), ha='center', va='center') # Place it on graph
      ax.title.set_text(title[subplot]) # Set the title for the graoh given as argument
    plt.show()

"""## Maze class"""

# This class define the Maze environment

class Maze(object):

  # [Action required]
  def __init__(self):
    """
    Maze initialisation.
    input: /
    output: /
    """
    
    # [Action required] Done
    # Properties set from the CID
    self._prob_success = 0.94 # float
    self._gamma = 0.84 # float
    self._goal = 1 # integer (0 for R0, 1 for R1, 2 for R2, 3 for R3)

    # Build the maze
    self._build_maze()
                              

  # Functions used to build the Maze environment 
  # You DO NOT NEED to modify them
  def _build_maze(self):
    """
    Maze initialisation.
    input: /
    output: /
    """

    # Properties of the maze
    self._shape = (13, 10)
    self._obstacle_locs = [
                          (1,0), (1,1), (1,2), (1,3), (1,4), (1,7), (1,8), (1,9), \
                          (2,1), (2,2), (2,3), (2,7), \
                          (3,1), (3,2), (3,3), (3,7), \
                          (4,1), (4,7), \
                          (5,1), (5,7), \
                          (6,5), (6,6), (6,7), \
                          (8,0), \
                          (9,0), (9,1), (9,2), (9,6), (9,7), (9,8), (9,9), \
                          (10,0)
                         ] # Location of obstacles
    self._absorbing_locs = [(2,0), (2,9), (10,1), (12,9)] # Location of absorbing states
    self._absorbing_rewards = [ (500 if (i == self._goal) else -50) for i in range (4) ]
    self._starting_locs = [(0,0), (0,1), (0,2), (0,3), (0,4), (0,5), (0,6), (0,7), (0,8), (0,9)] #Reward of absorbing states
    self._default_reward = -1 # Reward for each action performs in the environment
    self._max_t = 500 # Max number of steps in the environment

    # Actions
    self._action_size = 4
    self._direction_names = ['N','E','S','W'] # Direction 0 is 'N', 1 is 'E' and so on
        
    # States
    self._locations = []
    for i in range (self._shape[0]):
      for j in range (self._shape[1]):
        loc = (i,j) 
        # Adding the state to locations if it is no obstacle
        if self._is_location(loc):
          self._locations.append(loc)
    self._state_size = len(self._locations)

    # Neighbours - each line is a state, ranked by state-number, each column is a direction (N, E, S, W)
    self._neighbours = np.zeros((self._state_size, 4)) 
    
    for state in range(self._state_size):
      loc = self._get_loc_from_state(state)

      # North
      neighbour = (loc[0]-1, loc[1]) # North neighbours location
      if self._is_location(neighbour):
        self._neighbours[state][self._direction_names.index('N')] = self._get_state_from_loc(neighbour)
      else: # If there is no neighbour in this direction, coming back to current state
        self._neighbours[state][self._direction_names.index('N')] = state

      # East
      neighbour = (loc[0], loc[1]+1) # East neighbours location
      if self._is_location(neighbour):
        self._neighbours[state][self._direction_names.index('E')] = self._get_state_from_loc(neighbour)
      else: # If there is no neighbour in this direction, coming back to current state
        self._neighbours[state][self._direction_names.index('E')] = state

      # South
      neighbour = (loc[0]+1, loc[1]) # South neighbours location
      if self._is_location(neighbour):
        self._neighbours[state][self._direction_names.index('S')] = self._get_state_from_loc(neighbour)
      else: # If there is no neighbour in this direction, coming back to current state
        self._neighbours[state][self._direction_names.index('S')] = state

      # West
      neighbour = (loc[0], loc[1]-1) # West neighbours location
      if self._is_location(neighbour):
        self._neighbours[state][self._direction_names.index('W')] = self._get_state_from_loc(neighbour)
      else: # If there is no neighbour in this direction, coming back to current state
        self._neighbours[state][self._direction_names.index('W')] = state

    # Absorbing
    self._absorbing = np.zeros((1, self._state_size))
    for a in self._absorbing_locs:
      absorbing_state = self._get_state_from_loc(a)
      self._absorbing[0, absorbing_state] = 1

    # Transition matrix
    self._T = np.zeros((self._state_size, self._state_size, self._action_size)) # Empty matrix of domension S*S*A
    for action in range(self._action_size):
      for outcome in range(4): # For each direction (N, E, S, W)
        # The agent has prob_success probability to go in the correct direction
        if action == outcome:
          prob = 1 - 3.0 * ((1.0 - self._prob_success) / 3.0) # (theoritically equal to self.prob_success but avoid rounding error and garanty a sum of 1)
        # Equal probability to go into one of the other directions
        else:
          prob = (1.0 - self._prob_success) / 3.0
          
        # Write this probability in the transition matrix
        for prior_state in range(self._state_size):
          # If absorbing state, probability of 0 to go to any other states
          if not self._absorbing[0, prior_state]:
            post_state = self._neighbours[prior_state, outcome] # Post state number
            post_state = int(post_state) # Transform in integer to avoid error
            self._T[prior_state, post_state, action] += prob

    # Reward matrix
    self._R = np.ones((self._state_size, self._state_size, self._action_size)) # Matrix filled with 1
    self._R = self._default_reward * self._R # Set default_reward everywhere
    for i in range(len(self._absorbing_rewards)): # Set absorbing states rewards
      post_state = self._get_state_from_loc(self._absorbing_locs[i])
      self._R[:,post_state,:] = self._absorbing_rewards[i]

    # Creating the graphical Maze world
    self._graphics = GraphicsMaze(self._shape, self._locations, self._default_reward, self._obstacle_locs, self._absorbing_locs, self._absorbing_rewards, self._absorbing)
    
    # Reset the environment
    self.reset() # LIV: dunno this


  def _is_location(self, loc):
    """
    Is the location a valid state (not out of Maze and not an obstacle)
    input: loc {tuple} -- location of the state
    output: _ {bool} -- is the location a valid state
    """
    if (loc[0] < 0 or loc[1] < 0 or loc[0] > self._shape[0]-1 or loc[1] > self._shape[1]-1):
      return False
    elif (loc in self._obstacle_locs):
      return False
    else:
      return True


  def _get_state_from_loc(self, loc):
    """
    Get the state number corresponding to a given location
    input: loc {tuple} -- location of the state
    output: index {int} -- corresponding state number
    """
    return self._locations.index(tuple(loc))


  def _get_loc_from_state(self, state):
    """
    Get the state number corresponding to a given location
    input: index {int} -- state number
    output: loc {tuple} -- corresponding location
    """
    return self._locations[state]

  # Getter functions used only for DP agents
  # You DO NOT NEED to modify them
  def get_T(self):
    return self._T

  def get_R(self):
    return self._R

  def get_absorbing(self):
    return self._absorbing

  # Getter functions used for DP, MC and TD agents
  # You DO NOT NEED to modify them
  def get_graphics(self):
    return self._graphics

  def get_action_size(self):
    return self._action_size

  def get_state_size(self):
    return self._state_size

  def get_gamma(self):
    return self._gamma

  # Functions used to perform episodes in the Maze environment
  def reset(self):
    """
    Reset the environment state to one of the possible starting states
    input: /
    output: 
      - t {int} -- current timestep
      - state {int} -- current state of the envionment
      - reward {int} -- current reward
      - done {bool} -- True if reach a terminal state / 0 otherwise
    """
    self._t = 0
    self._state = self._get_state_from_loc(self._starting_locs[random.randrange(len(self._starting_locs))])
    self._reward = 0
    self._done = False
    return self._t, self._state, self._reward, self._done

  def step(self, action):
    """
    Perform an action in the environment
    input: action {int} -- action to perform
    output: 
      - t {int} -- current timestep
      - state {int} -- current state of the envionment
      - reward {int} -- current reward
      - done {bool} -- True if reach a terminal state / 0 otherwise
    """

    # If environment already finished, print an error
    if self._done or self._absorbing[0, self._state]:
      print("Please reset the environment")
      return self._t, self._state, self._reward, self._done

    # Drawing a random number used for probability of next state
    probability_success = random.uniform(0,1)

    # Look for the first possible next states (so get a reachable state even if probability_success = 0)
    new_state = 0
    while self._T[self._state, new_state, action] == 0: 
      new_state += 1
    assert self._T[self._state, new_state, action] != 0, "Selected initial state should be probability 0, something might be wrong in the environment." #no new state was found

    # Find the first state for which probability of occurence matches the random value
    total_probability = self._T[self._state, new_state, action]
    while (total_probability < probability_success) and (new_state < self._state_size-1): # ensures random walk, if total_probability is 0.7 there is a 0.7 chance that total_probability is bigger thn the random number
     new_state += 1 
     total_probability += self._T[self._state, new_state, action] # is 0 if new_state is non-reachable, will continue looping
    assert self._T[self._state, new_state, action] != 0, "Selected state should be probability 0, something might be wrong in the environment."
    
    # Setting new t, state, reward and done
    self._t += 1
    self._reward = self._R[self._state, new_state, action]
    self._done = self._absorbing[0, new_state] or self._t > self._max_t
    self._state = new_state
    return self._t, self._state, self._reward, self._done

"""## DP Agent"""

# This class defines the Dynamic Programing agent 

class DP_agent(object):

  def solve(self, env):
    """
    Solve a given Maze environment using Dynamic Programming
    input: env {Maze object} -- Maze to solve
    output: 
      - policy {np.array} -- Optimal policy found to solve the given Maze environment 
      - V {np.array} -- Corresponding value function 
    """
    
    # Initialisation
    policy = np.zeros((env.get_state_size(), env.get_action_size())) 
    V = np.zeros(env.get_state_size())

    policy, V = self.value_iteration(env, gamma = env.get_gamma(), threshold = 0.01) 

    return policy, V

  def value_iteration(self, env, gamma, threshold = 0.001):
    """
    Value iteration on GridWorld
    input: 
      - threshold {float} -- threshold value used to stop the value iteration algorithm
      - gamma {float} -- discount factor
    output: 
      - policy {np.array} -- optimal policy found using the value iteration algorithm
      - V {np.array} -- value function corresponding to the policy
      - epochs {int} -- number of epochs to find this policy
    """
    # Ensure gamma value is valid
    assert (gamma <=1) and (gamma >= 0), "Discount factor should be in [0, 1]."

    # Initialisation
    delta = threshold # Setting value of delta to go through the first breaking condition
    V = np.zeros(env.get_state_size()) # Initialise values at 0 for each state
    policy = np.zeros((env.get_state_size(), env.get_action_size())) 

    while delta >= threshold:
      delta = 0 # Reinitialise delta value, here to check if the value of the state that changed the most, changed less that the threshold set

      for prior_state in range(env.get_state_size()):
        if not env.get_absorbing()[0, prior_state]:

          # Store previos value for that state
          v = V[prior_state]

          # Compute Q value 
          Q = np.zeros(env.get_action_size())
          for post_state in range(env.get_state_size()):
            Q += env.get_T()[prior_state, post_state,:] * (env.get_R()[prior_state, post_state,:] + gamma * V[post_state])
          
          # New Value is the maximum of Q
          V[prior_state] = np.max(Q)
          
          # Compute the new delta
          delta = max(delta, np.abs(v - V[prior_state])) # delta is the difference of the value difference of the state that changed the most
    
    # end of while loop means we have the optimal value
    
    # Fill in optimal policy
    for prior_state in range(env.get_state_size()):
      Q = np.zeros(env.get_action_size())
      for post_state in range(env.get_state_size()):
        Q += env.get_T()[prior_state, post_state,:] * (env.get_R()[prior_state, post_state, :] + gamma * V[post_state])
      #print("Q: ", Q)
      #The action from state s to a state s' that maximises the Q value gets probability of 1
      policy[prior_state, np.argmax(Q)] = 1;
  
    return policy, V

"""## MC agent"""

# This class define the Monte-Carlo agent

class MC_agent(object):
  
  # [Action required]
  # WARNING: make sure this function can be called by the auto-marking script
  def solve(self, env):
    """
    Solve a given Maze environment using Monte Carlo learning
    input: env {Maze object} -- Maze to solve
    output: 
      - policy {np.array} -- Optimal policy found to solve the given Maze environment 
      - values {list of np.array} -- List of successive value functions for each episode 
      - total_rewards {list of float} -- Corresponding list of successive total non-discounted sum of reward for each episode  #MEANING of non-discounted???
    """

    # Initialisation (can be edited)
    policy, values, total_rewards = self.MC_firstvisit(env, episodes = 2000, alpha = 0.1, gamma = env.get_gamma())
     
    #### 
    # Add your code here
    # WARNING: this agent only has access to env.reset() and env.step()
    # You should not use env.get_T(), env.get_R() or env.get_absorbing() to compute any value
    ####
    
    return policy, values, total_rewards
  
  def MC_firstvisit(self, env, episodes, alpha, gamma):

    # Initialise 
    Q = np.random.rand(env.get_state_size(), env.get_action_size()) 
    V = np.zeros(env.get_state_size())
    values = [V.copy()]
    total_rewards = [] #array of lists (one list/state) OR LIST OF FLOAT
    N = np.zeros((env.get_state_size(), env.get_action_size())) 
    policy = np.zeros((env.get_state_size(), env.get_action_size())) 
    pi = np.zeros((env.get_state_size(), env.get_action_size()))

    for tao in range(episodes): 
      # Generate Trace (1 / episode)
      t, prior_state, reward, done = env.reset()
      trace = []
      epsilon = np.exp(-tao/500)
      
      while not done:
        # Choose action through epsilon-greedy action selection
        action = np.argmax(Q[prior_state, :])
        pi[prior_state, :] =  epsilon/env.get_action_size() 
        pi[prior_state, action] += 1-epsilon
        if np.random.uniform(0,1) < epsilon: #with probability epsilon choose an action at random
          action = random.randint(0,3)
        
        # Go to next step
        t, post_state, reward, done = env.step(action)
        trace.append([prior_state, action, reward])
        prior_state = post_state
      

      # Compute returns after each state-action pair and count occurrences of state-action pairs
      G_ndisc = 0
      G = 0
      G_disc = np.zeros((env.get_state_size(), env.get_action_size()))
      n = np.zeros((env.get_state_size(), env.get_action_size()))
      for i in reversed(range(0, len(trace))): 
        s_a_r = trace[i]
        # for index, s_a_r in enumerate(trace[::-1]): #looping through list reversedely  
        G = s_a_r[2] + gamma * G
        if not s_a_r in trace[:i]: # 
          G_disc[s_a_r[0], s_a_r[1]] = G # once done for all states in trace, G_disc will be the total discounted return from state 1
          G_ndisc = s_a_r[2] + G_ndisc 
          N[s_a_r[0], s_a_r[1]] += 1 # times this state action pair appears in all episodes
      total_rewards.append(G_ndisc)

      # unique_traces = [list(x) for x in set(tuple(x) for x in trace)]
      for i, s_a_r in enumerate(trace): 
        # for s_a_r in unique_traces: # change this
        if not s_a_r in trace[:i]: # 
          Q[s_a_r[0], s_a_r[1]] = Q[s_a_r[0], s_a_r[1]] + (1/N[s_a_r[0], s_a_r[1]]) * (G_disc[s_a_r[0], s_a_r[1]] - Q[s_a_r[0], s_a_r[1]])
          V[s_a_r[0]] = sum(pi[s_a_r[0], :] * Q[s_a_r[0], :])
      #print("Q: ", Q)

      # Update values
      if tao == 0:
        values = [V.copy()]
      else:
        values.append(values[-1].copy() + (1 / (tao+1)) * (V.copy() - values[-1].copy()))
      #print("V: ", V)
      #print("Values: ", values[tao])

    # Update policy
    for st in range(env.get_state_size()):
      policy[st, np.argmax(Q[st,:])] = 1 # The action that maximises the Q value gets probability 1 !doesn't reflect Q in the graphical representations!!!
    
    return policy, values, total_rewards

"""## TD agent"""

# This class defines the Temporal-Difference agent

class TD_agent(object):

  def solve(self, env):
    """
    Solve a given Maze environment using Temporal Difference learning
    input: env {Maze object} -- Maze to solve
    output: 
      - policy {np.array} -- Optimal policy found to solve the given Maze environment 
      - values {list of np.array} -- List of successive value functions for each episode 
      - total_rewards {list of float} -- Corresponding list of successive total non-discounted sum of reward for each episode 
    """

    # Initialisation (can be edited)
    policy, values, total_rewards = self.SARSA(env, episodes = 2000, alpha = 0.1, gamma = env.get_gamma())

    return policy, values, total_rewards
  
  def SARSA(self, env, episodes, alpha, gamma):
    Q = np.random.rand(env.get_state_size(), env.get_action_size()) 
    V = np.zeros(env.get_state_size())
    policy = np.zeros((env.get_state_size(), env.get_action_size())) 
    pi = np.zeros((env.get_state_size(), env.get_action_size()))
    values = [V.copy()]
    total_rewards = []

    for tao in range(episodes): 
      trace = []
      G_ndisc = 0

      # Generate Trace (1 / episode)
      t, s, reward, done = env.reset()

      # Choose first action 
      # epsilon = 1/((tao+1)) #**(1/4))
      epsilon = np.exp(-tao/500)
      a, pi = self.epsilon_greedy(env, Q, epsilon, s, pi)

      while not done:
        
        # Go to next step, observe reward  post state
        t, s_, reward, done = env.step(a)
        G_ndisc += reward
        a_, pi = self.epsilon_greedy(env, Q, epsilon, s_, pi)

        if done: 
          Q[s, a] += alpha * (reward  - Q[s, a])
        else:
          Q[s, a] += alpha * (reward + gamma * Q[s_, a_] - Q[s, a])

        V[s] = sum(pi[s, :] * Q[s, :])
        s, a = s_, a_
        # trace.append([prior_state, action, reward]) do we need to keep track of all the traces here?

      # Update values
      if tao == 0:
        values = [V.copy()]
      else:
        values.append(values[-1].copy() + (1 / (tao+1)) * (V.copy() - values[-1].copy()))

      # Append total reward of this trace
      total_rewards.append(G_ndisc)

    # Update policy
    for st in range(env.get_state_size()):
      policy[st, np.argmax(Q[st,:])] = 1 # The action that maximises the Q value gets probability 1 !doesn't reflect Q in the graphical representations!!!

    return policy, values, total_rewards

  
  def epsilon_greedy(self, env, Q, epsilon, prior_state, pi):
    action = np.argmax(Q[prior_state, :])
    pi[prior_state, :] =  epsilon/env.get_action_size() 
    pi[prior_state, action] += 1-epsilon
    if np.random.uniform(0,1) < epsilon: #with probability epsilon choose an action at random
      action = random.randint(0, env.get_action_size()-1)
    
    return action, pi

"""## Example main"""

# Example main (can be edited)

### Question 0: Defining the environment

print("Creating the Maze:\n")
maze = Maze()


### Question 1: Dynamic programming

dp_agent = DP_agent()
dp_policy, dp_value = dp_agent.solve(maze)

print("Results of the DP agent:\n")
maze.get_graphics().draw_policy(dp_policy)
maze.get_graphics().draw_value(dp_value)


### Question 2: Monte-Carlo learning

mc_agent = MC_agent()
mc_policy, mc_values, total_rewards = mc_agent.solve(maze)

print("Results of the MC agent:\n")
maze.get_graphics().draw_policy(mc_policy)
maze.get_graphics().draw_value(mc_values[-1])


### Question 3: Temporal-Difference learning

td_agent = TD_agent()
td_policy, td_values, total_rewards = td_agent.solve(maze)

print("Results of the TD agent:\n")
maze.get_graphics().draw_policy(td_policy)
maze.get_graphics().draw_value(td_values[-1])